import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Header from "../components/Header";
import ContentCard from "../components/ContentCard";
import Script from "next/script";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box>
          <ContentCard />
        </Box>
      </main>
    </>
  );
};

export default Home;
